export const recurringAllowanceManagerAddress =
  "0xf5A7dAB5046e2660Ab9CDAe19F2C054598668c44";
export const recurringAllowanceManagerAbi = [
  {
    type: "function",
    name: "ETHER",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "approve",
    inputs: [
      {
        name: "recurringAllowance",
        type: "tuple",
        internalType: "struct RecurringAllowanceManager.RecurringAllowance",
        components: [
          { name: "account", type: "address", internalType: "address" },
          { name: "spender", type: "address", internalType: "address" },
          { name: "token", type: "address", internalType: "address" },
          { name: "start", type: "uint48", internalType: "uint48" },
          { name: "end", type: "uint48", internalType: "uint48" },
          { name: "period", type: "uint48", internalType: "uint48" },
          { name: "allowance", type: "uint160", internalType: "uint160" },
        ],
      },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "decodeContext",
    inputs: [{ name: "context", type: "bytes", internalType: "bytes" }],
    outputs: [
      {
        name: "recurringAllowance",
        type: "tuple",
        internalType: "struct RecurringAllowanceManager.RecurringAllowance",
        components: [
          { name: "account", type: "address", internalType: "address" },
          { name: "spender", type: "address", internalType: "address" },
          { name: "token", type: "address", internalType: "address" },
          { name: "start", type: "uint48", internalType: "uint48" },
          { name: "end", type: "uint48", internalType: "uint48" },
          { name: "period", type: "uint48", internalType: "uint48" },
          { name: "allowance", type: "uint160", internalType: "uint160" },
        ],
      },
      { name: "signature", type: "bytes", internalType: "bytes" },
    ],
    stateMutability: "pure",
  },
  {
    type: "function",
    name: "getCurrentCycle",
    inputs: [
      {
        name: "recurringAllowance",
        type: "tuple",
        internalType: "struct RecurringAllowanceManager.RecurringAllowance",
        components: [
          { name: "account", type: "address", internalType: "address" },
          { name: "spender", type: "address", internalType: "address" },
          { name: "token", type: "address", internalType: "address" },
          { name: "start", type: "uint48", internalType: "uint48" },
          { name: "end", type: "uint48", internalType: "uint48" },
          { name: "period", type: "uint48", internalType: "uint48" },
          { name: "allowance", type: "uint160", internalType: "uint160" },
        ],
      },
    ],
    outputs: [
      {
        name: "",
        type: "tuple",
        internalType: "struct RecurringAllowanceManager.CycleUsage",
        components: [
          { name: "start", type: "uint48", internalType: "uint48" },
          { name: "end", type: "uint48", internalType: "uint48" },
          { name: "spend", type: "uint160", internalType: "uint160" },
        ],
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getHash",
    inputs: [
      {
        name: "recurringAllowance",
        type: "tuple",
        internalType: "struct RecurringAllowanceManager.RecurringAllowance",
        components: [
          { name: "account", type: "address", internalType: "address" },
          { name: "spender", type: "address", internalType: "address" },
          { name: "token", type: "address", internalType: "address" },
          { name: "start", type: "uint48", internalType: "uint48" },
          { name: "end", type: "uint48", internalType: "uint48" },
          { name: "period", type: "uint48", internalType: "uint48" },
          { name: "allowance", type: "uint160", internalType: "uint160" },
        ],
      },
    ],
    outputs: [{ name: "", type: "bytes32", internalType: "bytes32" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "isAuthorized",
    inputs: [
      {
        name: "recurringAllowance",
        type: "tuple",
        internalType: "struct RecurringAllowanceManager.RecurringAllowance",
        components: [
          { name: "account", type: "address", internalType: "address" },
          { name: "spender", type: "address", internalType: "address" },
          { name: "token", type: "address", internalType: "address" },
          { name: "start", type: "uint48", internalType: "uint48" },
          { name: "end", type: "uint48", internalType: "uint48" },
          { name: "period", type: "uint48", internalType: "uint48" },
          { name: "allowance", type: "uint160", internalType: "uint160" },
        ],
      },
    ],
    outputs: [{ name: "", type: "bool", internalType: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "permit",
    inputs: [
      {
        name: "recurringAllowance",
        type: "tuple",
        internalType: "struct RecurringAllowanceManager.RecurringAllowance",
        components: [
          { name: "account", type: "address", internalType: "address" },
          { name: "spender", type: "address", internalType: "address" },
          { name: "token", type: "address", internalType: "address" },
          { name: "start", type: "uint48", internalType: "uint48" },
          { name: "end", type: "uint48", internalType: "uint48" },
          { name: "period", type: "uint48", internalType: "uint48" },
          { name: "allowance", type: "uint160", internalType: "uint160" },
        ],
      },
      { name: "signature", type: "bytes", internalType: "bytes" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "revoke",
    inputs: [
      {
        name: "recurringAllowance",
        type: "tuple",
        internalType: "struct RecurringAllowanceManager.RecurringAllowance",
        components: [
          { name: "account", type: "address", internalType: "address" },
          { name: "spender", type: "address", internalType: "address" },
          { name: "token", type: "address", internalType: "address" },
          { name: "start", type: "uint48", internalType: "uint48" },
          { name: "end", type: "uint48", internalType: "uint48" },
          { name: "period", type: "uint48", internalType: "uint48" },
          { name: "allowance", type: "uint160", internalType: "uint160" },
        ],
      },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "withdraw",
    inputs: [
      { name: "context", type: "bytes", internalType: "bytes" },
      { name: "recipient", type: "address", internalType: "address" },
      { name: "value", type: "uint160", internalType: "uint160" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "withdraw",
    inputs: [
      {
        name: "recurringAllowance",
        type: "tuple",
        internalType: "struct RecurringAllowanceManager.RecurringAllowance",
        components: [
          { name: "account", type: "address", internalType: "address" },
          { name: "spender", type: "address", internalType: "address" },
          { name: "token", type: "address", internalType: "address" },
          { name: "start", type: "uint48", internalType: "uint48" },
          { name: "end", type: "uint48", internalType: "uint48" },
          { name: "period", type: "uint48", internalType: "uint48" },
          { name: "allowance", type: "uint160", internalType: "uint160" },
        ],
      },
      { name: "recipient", type: "address", internalType: "address" },
      { name: "value", type: "uint160", internalType: "uint160" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "event",
    name: "RecurringAllowanceApproved",
    inputs: [
      {
        name: "hash",
        type: "bytes32",
        indexed: true,
        internalType: "bytes32",
      },
      {
        name: "account",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "recurringAllowance",
        type: "tuple",
        indexed: false,
        internalType: "struct RecurringAllowanceManager.RecurringAllowance",
        components: [
          { name: "account", type: "address", internalType: "address" },
          { name: "spender", type: "address", internalType: "address" },
          { name: "token", type: "address", internalType: "address" },
          { name: "start", type: "uint48", internalType: "uint48" },
          { name: "end", type: "uint48", internalType: "uint48" },
          { name: "period", type: "uint48", internalType: "uint48" },
          { name: "allowance", type: "uint160", internalType: "uint160" },
        ],
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "RecurringAllowanceRevoked",
    inputs: [
      {
        name: "hash",
        type: "bytes32",
        indexed: true,
        internalType: "bytes32",
      },
      {
        name: "account",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "recurringAllowance",
        type: "tuple",
        indexed: false,
        internalType: "struct RecurringAllowanceManager.RecurringAllowance",
        components: [
          { name: "account", type: "address", internalType: "address" },
          { name: "spender", type: "address", internalType: "address" },
          { name: "token", type: "address", internalType: "address" },
          { name: "start", type: "uint48", internalType: "uint48" },
          { name: "end", type: "uint48", internalType: "uint48" },
          { name: "period", type: "uint48", internalType: "uint48" },
          { name: "allowance", type: "uint160", internalType: "uint160" },
        ],
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "RecurringAllowanceWithdrawn",
    inputs: [
      {
        name: "hash",
        type: "bytes32",
        indexed: true,
        internalType: "bytes32",
      },
      {
        name: "account",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "token",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "newUsage",
        type: "tuple",
        indexed: false,
        internalType: "struct RecurringAllowanceManager.CycleUsage",
        components: [
          { name: "start", type: "uint48", internalType: "uint48" },
          { name: "end", type: "uint48", internalType: "uint48" },
          { name: "spend", type: "uint160", internalType: "uint160" },
        ],
      },
    ],
    anonymous: false,
  },
  {
    type: "error",
    name: "AfterRecurringAllowanceEnd",
    inputs: [{ name: "end", type: "uint48", internalType: "uint48" }],
  },
  {
    type: "error",
    name: "BeforeRecurringAllowanceStart",
    inputs: [{ name: "start", type: "uint48", internalType: "uint48" }],
  },
  {
    type: "error",
    name: "ExceededRecurringAllowance",
    inputs: [
      { name: "value", type: "uint256", internalType: "uint256" },
      { name: "allowance", type: "uint256", internalType: "uint256" },
    ],
  },
  {
    type: "error",
    name: "InvalidSender",
    inputs: [{ name: "sender", type: "address", internalType: "address" }],
  },
  { type: "error", name: "Unauthorized", inputs: [] },
  {
    type: "error",
    name: "WithdrawValueOverflow",
    inputs: [{ name: "value", type: "uint256", internalType: "uint256" }],
  },
];
